### ISSUE TITLE
Syntax Hightlighting Issues Around `%`

### ISSUE THREAD

**Issue by CTC97** [crystal-lang-tools/zed-crystal#4] opened 2024-12-06 02:11 UTC
Thank you for doing the syntax highlighting for Crystal, you're the best! 

It looks like the highlighter fails after encountering "%".

Example shown below, in my color scheme everything after "%" is highlighted yellow.:

<img width="826" alt="image" src="https://github.com/user-attachments/assets/c48a58e3-26c0-4489-a23f-b611bb9aaa1d">

**Comment by nobodywasishere** [comment] 2024-12-06 02:32
This is a known issue. We're currently using the ruby tree sitter due to not having a good-enough crystal tree sitter yet, so macros don't work

**Comment by nobodywasishere** [comment] 2024-12-06 20:22
Closing as a duplicate of #2

**Closed as not planned by nobodywasishere** 2024-12-06 20:22 UTC
